// Generated by CoffeeScript 1.8.0

/*
 * El script esta encapsulado en una funcion anónima autoejecutable
 * para evitar conflictos con otras librerias.
 */

(function() {
  jQuery.noConflict();

  (function($) {

    /*
     ************************************************************************
     *****************************  $Contenido  *****************************
     * + Contenido
     *
     * + enlazarEventos
     * + 
     * + clientesEstablecer
     * + clientesGeneraLista
     * + clientesObtenerLista
     * + clientesObtenerUno
     * + clientesSeleccionar
     * + 
     * + 
     * + 
     * + 
     * + document.ready()
     * + windows.load()
     */
    var actualizaTotales, addArticulo, anular, cambiarLista, clearForm, clientesEstablecer, clientesGeneraLista, clientesObtenerLista, clientesObtenerUno, clientesSeleccionar, deleteRow, enlazarEventos, getArticulo, imprimir, procesarStocks, setCantidad;
    enlazarEventos = function() {

      /* Eventos Globales para todo el documento */
      $(window).on("beforeunload", function(e) {
        return "Todos los datos actuales se perderan si continúa.";
      });
      $("body").on("keydown", function(e) {
        if (e.keyCode === 118) {
          imprimir();
          return false;
        } else if (e.keyCode === 117) {
          anular();
          return false;
        }
        return null;
      });

      /* Botones */
      $("#search-clientes").on("click", function(e) {
        e.preventDefault();
        clientesObtenerLista();
        return null;
      });
      $(".cambiar-listas label").on("click", function(e) {
        e.preventDefault();
        cambiarLista(e);
        return null;
      });
      $("#imprimir").on("click", function(e) {
        e.preventDefault();
        imprimir();
        return null;
      });
      $("#anular").on("click", function(e) {
        e.preventDefault();
        anular();
        return null;
      });
      $("body").on("click", ".list-cli-row", function(e) {
        e.preventDefault();
        clientesSeleccionar($(this));
        return null;
      });
      $("body").on("click", ".delete-row", function(e) {
        e.preventDefault();
        deleteRow($(this));
        return null;
      });
      $("#clear-form").on("click", function(e) {
        e.preventDefault();
        clearForm();
        return null;
      });

      /* Acciones en campos */
      $("#cod-cliente").on("blur", function(e) {
        clientesObtenerUno($(this));
        return null;
      });
      $("#articulo-codigo").on("blur", function(e) {
        getArticulo($(this));
        return null;
      });
      $("#articulo-cantidad").on("keyup", function(e) {
        setCantidad($(this));
        return null;
      });
      $("#articulo-cantidad").on("keydown", function(e) {
        addArticulo(e);
        return null;
      });
      return null;
    };
    clientesEstablecer = function(nombre, direccion) {
      $("#datos-cliente").html("" + nombre + "<br><small>" + direccion + "</small>");
      return null;
    };
    clientesGeneraLista = function(list) {
      $("#modal-clientes .modal-body tbody").html("");
      $.each(list, function(key, value) {
        return $("#modal-clientes .modal-body tbody").append("<tr class='list-cli-row' data-clicod='" + key + "' data-clinom='" + value.nombre + "' data-clidir='" + value.direccion + "' > <td>" + key + "</td> <td>" + value.nombre + "</td> <td>" + value.direccion + "</td> </tr>");
      });
      $("#modal-clientes").modal('show');
      return null;
    };
    clientesObtenerLista = function() {
      var data;
      data = {
        'accion': "obtener-clientes",
        'data': {}
      };
      $.ajax({
        data: '&json=' + JSON.stringify(data),
        success: function(data, status, xhr) {
          var obj;
          obj = $.parseJSON(data);
          return clientesGeneraLista(obj.data);
        },
        type: 'POST',
        url: "libs/ajax.php"
      });
      return null;
    };
    clientesObtenerUno = function(elm) {
      var data, val;
      val = elm.val();
      data = {
        'accion': "obtener-cliente",
        'data': {}
      };
      data.data['cliente_codcli'] = val;
      if (val !== '') {
        $.ajax({
          data: '&json=' + JSON.stringify(data),
          success: function(data, status, xhr) {
            var obj;
            obj = $.parseJSON(data);
            if (obj.estado === "exito") {
              return clientesEstablecer(obj.data.nombre, obj.data.direccion);
            } else if (obj.estado === "error") {
              return console.error("Error al obtener el cliente.");
            }
          },
          type: 'POST',
          url: "libs/ajax.php"
        });
        return null;
      }
      return null;
    };
    clientesSeleccionar = function(elm) {
      $("#cod-cliente").val(elm.data("clicod"));
      clientesEstablecer(elm.data("clinom"), elm.data("clidir"));
      $("#modal-clientes").modal('hide');
      return null;
    };
    getArticulo = function(elm) {
      var data, val;
      val = elm.val();
      data = {
        'accion': "obtener-articulo",
        'data': {}
      };
      data.data['articulo_codart'] = val;
      if (val !== '') {
        $.ajax({
          beforeSend: function(xhr, settings) {
            return null;
          },
          complete: function(xhr, status) {
            return null;
          },
          data: '&json=' + JSON.stringify(data),
          success: function(data, status, xhr) {
            var obj, precio1, precio2, precio3, precioFormat;
            obj = $.parseJSON(data);
            precio1 = obj.data.precio.lista1;
            precio2 = obj.data.precio.lista2;
            precio3 = obj.data.precio.lista3;
            if ($("#lista1").parent().hasClass("active")) {
              precioFormat = numeral(precio1).format("$ 0,0.00");
            } else if ($("#lista2").parent().hasClass("active")) {
              precioFormat = numeral(precio2).format("$ 0,0.00");
            } else if ($("#lista3").parent().hasClass("active")) {
              precioFormat = numeral(precio3).format("$ 0,0.00");
            }
            if (obj.estado === "exito") {
              $("#articulo-denominacion").html("" + obj.data.denominacion);
              $("#articulo-precio").html("" + precioFormat);
              $("#articulo-precio").data("precio1", "" + precio1);
              $("#articulo-precio").data("precio2", "" + precio2);
              $("#articulo-precio").data("precio3", "" + precio3);
              return $("#articulo-importe").html("" + precioFormat);
            }
          },
          type: 'POST',
          url: "libs/ajax.php"
        });
        return null;
      }
    };
    setCantidad = function(elm) {
      var cant, cantidad, importe, importeFormat, precio;
      if ($("#articulo-codigo").val() !== "") {
        cantidad = elm.val();
        if (cantidad === "") {
          cantidad = "1";
        }
        elm.parent().data("value", cantidad);
        cant = parseFloat(cantidad);
        if ($("#lista1").parent().hasClass("active")) {
          precio = parseFloat($("#articulo-precio").data("precio1"));
        } else if ($("#lista2").parent().hasClass("active")) {
          precio = parseFloat($("#articulo-precio").data("precio2"));
        } else if ($("#lista3").parent().hasClass("active")) {
          precio = parseFloat($("#articulo-precio").data("precio3"));
        }
        importe = cant * precio;
        importeFormat = numeral(importe).format("$ 0,0.00");
        $("#articulo-importe").data("value", "" + importe);
        $("#articulo-importe").html("" + importeFormat);
      }
      return null;
    };
    addArticulo = function(evt) {
      var cantidad, codigo, denominacion, importe, importeFormat, precio1, precio2, precio3, precioFormat;
      if (evt.keyCode === 9 || evt.keyCode === 13) {
        codigo = $("#articulo-codigo").val();
        cantidad = $("#articulo-cantidad").val();
        denominacion = $("#articulo-denominacion").html();
        precio1 = $("#articulo-precio").data("precio1");
        precio2 = $("#articulo-precio").data("precio2");
        precio3 = $("#articulo-precio").data("precio3");
        precioFormat = $("#articulo-precio").html();
        importe = $("#articulo-importe").data("value");
        importeFormat = $("#articulo-importe").html();
        if (codigo !== "") {
          if (cantidad === "") {
            $("#articulo-cantidad").val("1");
            cantidad = "1";
          }
          $(".articulos tbody").append("<tr> <td class='codigo'>" + codigo + "</td> <td class='text-center cantidad' data-value='" + cantidad + "' >" + cantidad + "</td> <td>" + denominacion + "</td> <td class='text-right precio' data-precio1='" + precio1 + "' data-precio2='" + precio2 + "' data-precio3='" + precio3 + "' > " + precioFormat + " </td> <td class='text-right importe' data-value='" + importe + "' > " + importeFormat + " </td> <td class='text-right acc'> <a class='btn btn-danger delete-row' href='#'> <i class='fa fa-trash'></i> </a> </td> </tr>");
          evt.preventDefault();
          actualizaTotales();
          return clearForm();
        }
      }
    };
    clearForm = function() {
      $("#articulo-codigo").val("");
      $("#articulo-cantidad").val("");
      $("#articulo-cantidad").data("value", "");
      $("#articulo-denominacion").html("");
      $("#articulo-precio").html("$ 0,00");
      $("#articulo-precio").data("precio1", "0");
      $("#articulo-precio").data("precio2", "0");
      $("#articulo-precio").data("precio3", "0");
      $("#articulo-importe").html("$ 0,00");
      return $("#articulo-codigo").focus();
    };
    deleteRow = function(elm) {
      elm.parents("tr").remove();
      actualizaTotales();
      return clearForm();
    };
    actualizaTotales = function() {
      var total, totalFormat;
      total = 0;
      $(".articulos tbody tr").each(function(i) {
        return total += parseFloat($(this).find("td.importe").data("value"));
      });
      totalFormat = numeral(total).format("$ 0,0.00");
      $("#total").html(totalFormat);
      return $("#contar").html($(".articulos tbody tr").length);
    };
    cambiarLista = function(evt) {
      var lista;
      lista = $(evt.target).find('input').attr('id').replace("lista", "precio");
      $(".articulos tr").each(function(i) {
        var cantidad, importe, importeFormat, precio, precioFormat;
        cantidad = $(this).find(".cantidad").data("value");
        precio = $(this).find(".precio").data(lista);
        precioFormat = numeral(precio).format("$ 0,0.00");
        importe = cantidad * precio;
        importeFormat = numeral(importe).format("$ 0,0.00");
        $(this).find(".precio").html("" + precioFormat);
        $(this).find(".importe").data("value", "" + importe);
        return $(this).find(".importe").html("" + importeFormat);
      });
      return actualizaTotales();
    };
    imprimir = function() {
      if (confirm("¿Confirma que desea imprimir el recibo y procesar el stock?\n\n Total: " + ($("#total").html()) + "\n Cantidad de Artículos: " + ($("#contar").html()))) {
        return procesarStocks();
      }
    };
    anular = function() {
      clearForm();
      $("#cod-cliente").val("");
      $("#datos-cliente").html("Cliente<br><small>Dirección</small>");
      $(".articulos tbody").html("");
      actualizaTotales();
      $(".cambiar-listas label").removeClass("active");
      $($(".cambiar-listas label")[0]).addClass("active");
      return $("#cod-cliente").focus();
    };
    procesarStocks = function() {
      var articulos, data;
      data = {
        'accion': "actualizar-stock",
        'data': {}
      };
      articulos = [];
      $(".articulos tbody tr").each(function(i) {
        return articulos.push({
          "codigo": $(this).find("td.codigo").html(),
          "cantidad": $(this).find("td.cantidad").data("value")
        });
      });
      data.data['articulos'] = articulos;
      $.ajax({
        beforeSend: function(xhr, settings) {
          return null;
        },
        complete: function(xhr, status) {
          return null;
        },
        data: '&json=' + JSON.stringify(data),
        success: function(data, status, xhr) {
          var obj;
          obj = $.parseJSON(data);
          if (obj.estado === "exito") {
            window.print();
            return anular();
          } else {
            return alert("Error al procesar stocks");
          }
        },
        type: 'POST',
        url: "libs/ajax.php"
      });
      return null;
    };

    /* begin $( document ).ready() block. */
    $(function() {
      enlazarEventos();
      numeral.language('es', {
        delimiters: {
          thousands: '.',
          decimal: ','
        },
        currency: {
          symbol: '$'
        }
      });
      numeral.language('es');
      $.ajax({
        data: 'ajax=1',
        success: function(data, status, xhr) {
          var obj;
          obj = $.parseJSON(data);
          $("#empresa_nombre").html("" + obj.empresa_nombre);
          return $("#developed_by").html("" + obj.developed_by);
        },
        type: 'POST',
        url: "config.php"
      });
      return null;
    });

    /* end $( document ).ready() block. */

    /* begin $( window ).load() block. */
    $(window).load(function() {});

    /* end $( window ).load() block. */
    return null;
  })(jQuery);

}).call(this);
